name: Caching and Artifacts

on:
  workflow_dispatch:

jobs:

  uses-axios:
    runs-on: ubuntu-latest
    steps:

      - name: Get code
        uses: actions/checkout@v4
      

      - name: Caching Dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache
            ${{ runner.os }}-

      - name: Cache Output
        run: echo "${{ toJSON(steps.cache-dependencies.outputs) }}"

      - name: Install Dependencies
        run: |
          npm install
      
      - name: Run tests
        run: |
          npm test

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: code-coverage
          path: ./coverage
          retention-days: 10
      
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: code-coverage
          path: code-coverage-report
        
      - name: list
        run: ls -la
      
      - name: List to code-coverage-report
        working-directory: code-coverage-report
        run: ls -la

      - name: list again
        run: ls -la

      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/', { headers : { Accept: 'text/plain' } })
            console.log(res.data)

