name: Caching and Artifacts

on:
  workflow_dispatch:

jobs:

  uses-axios:
    runs-on: ubuntu-latest
    steps:

      - name: Get code
        uses: actions/checkout@v4
      

      - name: Caching Dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: "npm-cache"

      - name: Cache Output
        run: echo "${{ toJSON(steps.cache-dependencies.outputs) }}"

      - name: Install Dependencies
        run: |
          npm install

      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/', { headers : { Accept: 'text/plain' } })
            console.log(res.data)

