name: Calling Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: Input description
        type: string
        default: 'Ali'
        required: false

jobs:
  calling-a-reusable-wf:
    uses: joaok2k2/called-workflow/.github/workflows/reusable.yml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
  
  calling-a-reusable-wf-in-the-same-repo:
    uses: ./.github/workflows/reusable-workflow.yml
  
  using-resuable-wf-output:
    needs: calling-a-reusable-wf-in-the-same-repo
    runs-on: ubuntu-latest
    steps:
      - name: Date Output
        run: echo "${{  needs.calling-a-reusable-wf-in-the-same-repo.outputs.date }}"
