name: Concurrency 1

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true
        
concurrency: concurrency-1
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 30
        run: sleep 30
