name: Docker containers

on: workflow_dispatch

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      env:
        API_URL: some-url.com
      ports:
        - 80
      # volumes: 
      #   - vol_name: /path/in/container # volume name
      #   - /path/to/container # anonymous volume
      #   - /path/in/host:/path/in/container # bind mound volume
      # options: --cpus 1

    steps:
      - name: Log Node & OS Verisons
        run: |
          node -v
          cat /etc/os-release
     
      - name: Log env
        run: echo $API_URL