name: Docker containers

on: workflow_dispatch

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      env:
        API_URL: some-url.com
      ports:
        - 80
      # volumes: 
      #   - vol_name: /path/in/container # volume name
      #   - /path/to/container # anonymous volume
      #   - /path/in/host:/path/in/container # bind mound volume
      # options: --cpus 1

    steps:
      - name: Log Node & OS Verisons
        run: |
          node -v
          cat /etc/os-release
     
      - name: Log env
        run: echo $API_URL

      - name: Creating a file
        run: |
          echo "Some words to people who knows how to use envsubst" > helloMySTB2024.txt
      
      - name: Container in a steps
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+3

      - name: Log node version
        uses: docker://node:18.16-alpine3.17
        with:
          args: -v
      
      - name: Show file contents
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: cat
          args: helloMySTB2024.txt
      
      - name: Listing directory
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: ls
          args: .

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Execute Script
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: "./script.sh"
          args: "Teste de script"
      
      - name: Send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: POC from Github Actions
          SLACK_MESSAGE: "Actor ${{ github.actor }}, Event: ${{ github.event_name }}" 
          SLACK_COLOR: "#723fc4"     


      