name: Environments and Secrets.

on: push

jobs:
  decrypt-file:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      
      - name: Decrypt File
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" \
          --output $HOME/secrets/palmeiras.json \
          file_secret.json.gpg
      
      - name: Reading Decrypted File
        run: |
          cat $HOME/secrets/palmeiras.json



