name: Matrix

on:
  push:
    branches:
      - main

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Check node
        run: node -v

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Check node
        run: node -v