name: Matrix

on:
  push:
    branches:
      - main

jobs:
  node-matrix:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest]
        node-version: [16,18,20]
    runs-on: matrix.os
    steps:
      - name: Check node
        run: node -v

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check node
        run: node -v