name: Matrix

on:
  push:
    branches:
      - main

jobs:
  node-matrix:
    continue-on-error: true
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest]
        node-version: [16, 18, 20]
      fail-fast: true
      max-parallel: 6
    runs-on: ${{ matrix.os }}
    steps:
      
      - name: Check node
        run: node -v

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      
      - name: test fail-fast
        if: matrix.node-version == 16
        run: |
          sleep 60

      - name: test fail-fast
        if: matrix.node-version == 18
        run: |
          exit 1

      - name: Check node
        run: node -v