name: Matrix

on:
  push:
    branches:
      - main

jobs:
  node-matrix:
    continue-on-error: false
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest]
        node-version: [16, 18, 20]
      fail-fast: false
      max-parallel: 6
    runs-on: ${{ matrix.os }}
    steps:
      
      - name: Check node
        run: node -v

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: test fail-fast
        if: matrix.node-version == 18
        run: |
          echo ${{ matrix.node-version }}

      - name: Check node
        run: node -v